### ISSUE TITLE
Notifications from form to db

### ISSUE THREAD

**Issue by anthonyargatoff** [anthonyargatoff/LifeCycle-Thugs#128]
Receive the notification data from the front end. Parse the data into the attribute string and put in database

Specific - Implement class to handle user input from form, parse into attribute string, put in database
Measurable - Get user input from front-end, put in back-end
Assignable - 
Realistic - User will be able to set notification, data base receives entry
Time-related - Will take a sprint cycle

**Comment by DyPickard** [comment]
Wondering about this issue. Is this for user adding new notification subscription?
If so, I have an issue already completed for that.
