### ISSUE TITLE
Search Form Input

### ISSUE THREAD

**Issue by anthonyargatoff** [anthonyargatoff/LifeCycle-Thugs#143]
@DyPickard can you make these adjustments to the front end form:
- For location search, add latitude, longitude and radius user input
- For date, can you make an entry for a startdate and an endate?
- Magnitude is fine.

Specific - create input on search page
Measurable - user can select different parameters to query
Assignable - Dylan
Realistic - Get user input working
Time-related - Take 4 hours

**Comment by DyPickard** [comment]
will do

**Comment by DyPickard** [comment]
@anthonyargatoff this is what it looks like at the moment. Let me know what you think. 

![Image](https://github.com/anthonyargatoff/LifeCycle-Thugs/assets/110944869/5d072aef-2d0d-4b18-bc73-0c8a7f39fd33)
