### ISSUE TITLE
Create documentation to run flask app

### ISSUE THREAD

**Issue by anthonyargatoff** [anthonyargatoff/LifeCycle-Thugs#86]
It's not clear to me on how to run our flask application.

Set up a readme.md in the flask directory with instructions on how to start and manage the flask application.

Specific - Flask documentation
Measurable - Adding info to the readme
Assignable - Varun, Aayush
Realistic - Documentation will cover how to install, start, view, and close the application
Time-related - will take a single sprint cycle

**Comment by Varun2711** [comment]
assigned work has been completed
